/**
 * niagaDataService.js
 * Service layer to handle Niaga (Commercial) KPI data from database.
 */
import api from './api';

const MONTHS_SHORT = { 
  1:'Jan', 2:'Feb', 3:'Mar', 4:'Apr', 5:'Mei', 6:'Jun', 
  7:'Jul', 8:'Ags', 9:'Sep', 10:'Okt', 11:'Nov', 12:'Des' 
};

const MONTH_WEIGHTS = [0.077, 0.074, 0.082, 0.080, 0.083, 0.081, 0.086, 0.088, 0.085, 0.084, 0.083, 0.077];

export async function getNiagaData(year = 2026) {
  // 1. Fetch annual targets from DB
  let targetPelunasan = 40.0; // Rp Miliar
  let targetPenghapusan = 30.0; // Rp Miliar
  let targetLbkb = 30.0; // Laporan

  try {
    const targetsRes = await api.get(`/targets?tahun=${year}`);
    const dbTargets = targetsRes.data || [];
    
    const pel = dbTargets.find(t => t.indikator === 'Pelunasan PRR & Piutang');
    if (pel) targetPelunasan = parseFloat(pel.target);

    const pen = dbTargets.find(t => t.indikator === 'Penghapusan PRR');
    if (pen) targetPenghapusan = parseFloat(pen.target);

    const lbkb = dbTargets.find(t => t.indikator === 'Tindak Lanjut LBKB');
    if (lbkb) targetLbkb = parseFloat(lbkb.target);
  } catch (e) {
    console.warn("Failed to fetch Niaga targets, using fallback defaults", e);
  }

  // 2. Fetch monthly realisations from DB
  const realMap = {};
  try {
    const res = await api.get(`/kinerja/niaga?tahun=${year}`);
    if (res.data && Array.isArray(res.data)) {
      res.data.forEach(item => {
        if (item.periode) {
          const raw = item.data_realisasi;
          realMap[item.periode.bulan] = raw != null && (typeof raw === 'object' || Array.isArray(raw))
            ? raw
            : JSON.parse(raw || '{}');
        }
      });
    }
  } catch (e) {
    console.warn("Failed to fetch Niaga realisations from backend", e);
  }

  // 3. Build 12-month data
  const rows = [];
  for (let m = 1; m <= 12; m++) {
    const w = MONTH_WEIGHTS[m - 1];
    const real = realMap[m] || null;

    // Monthly targets
    const tgtPelunasan = targetPelunasan * w;
    const tgtPenghapusan = targetPenghapusan * w;
    const tgtLbkb = targetLbkb * w;

    // Monthly realisations (keys mapped to snake_case equivalent generated by Input page)
    const realPelunasan = real && real['pelunasan_prr_&_piutang'] !== undefined ? parseFloat(real['pelunasan_prr_&_piutang']) : null;
    const realPenghapusan = real && real['penghapusan_prr'] !== undefined ? parseFloat(real['penghapusan_prr']) : null;
    const realLbkb = real && real['tindak_lanjut_lbkb'] !== undefined ? parseFloat(real['tindak_lanjut_lbkb']) : null;

    rows.push({
      bulan: m,
      label: MONTHS_SHORT[m],
      
      pelunasan_target: tgtPelunasan,
      pelunasan_real: realPelunasan,

      penghapusan_target: tgtPenghapusan,
      penghapusan_real: realPenghapusan,

      lbkb_target: tgtLbkb,
      lbkb_real: realLbkb,

      _hasData: !!real,
    });
  }

  // Calculate cumulative values
  let cumPelunasanTgt = 0, cumPelunasanReal = 0;
  let cumPenghapusanTgt = 0, cumPenghapusanReal = 0;
  let cumLbkbTgt = 0, cumLbkbReal = 0;

  rows.forEach(r => {
    cumPelunasanTgt += r.pelunasan_target;
    if (r.pelunasan_real !== null) cumPelunasanReal += r.pelunasan_real;

    cumPenghapusanTgt += r.penghapusan_target;
    if (r.penghapusan_real !== null) cumPenghapusanReal += r.penghapusan_real;

    cumLbkbTgt += r.lbkb_target;
    if (r.lbkb_real !== null) cumLbkbReal += r.lbkb_real;

    r.c_pelunasan_target = cumPelunasanTgt;
    r.c_pelunasan_real = r.pelunasan_real !== null ? cumPelunasanReal : null;

    r.c_penghapusan_target = cumPenghapusanTgt;
    r.c_penghapusan_real = r.penghapusan_real !== null ? cumPenghapusanReal : null;

    r.c_lbkb_target = cumLbkbTgt;
    r.c_lbkb_real = r.lbkb_real !== null ? cumLbkbReal : null;
  });

  return rows;
}
