<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TargetTahunanSeeder extends Seeder
{
    public function run(): void
    {
        // Clear existing data to avoid duplicates
        DB::table('targets')->truncate();

        $data = [
            [
                'id' => 8,
                'bidang' => 'Pemasaran',
                'indikator' => 'Pendapatan BP',
                'satuan' => 'Rp Miliar',
                'polaritas' => 'MAXIMIZE',
                'bobot' => 25.00,
                'target' => null,
                'tahun' => 2026,
                'target_jan' => null,
                'target_feb' => null,
                'target_mar' => null,
                'target_apr' => null,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 9,
                'bidang' => 'Aset',
                'indikator' => 'Pengembangan Aset Distribusi',
                'satuan' => 'Unit',
                'polaritas' => 'MAXIMIZE',
                'bobot' => 40.00,
                'target' => null,
                'tahun' => 2026,
                'target_jan' => null,
                'target_feb' => null,
                'target_mar' => null,
                'target_apr' => null,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 10,
                'bidang' => 'Keuangan',
                'indikator' => 'Pengendalian Anggaran',
                'satuan' => '%',
                'polaritas' => 'MAXIMIZE',
                'bobot' => 30.00,
                'target' => null,
                'tahun' => 2026,
                'target_jan' => null,
                'target_feb' => null,
                'target_mar' => null,
                'target_apr' => null,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 11,
                'bidang' => 'Niaga',
                'indikator' => 'Penghapusan PRR',
                'satuan' => 'Rp Miliar',
                'polaritas' => 'MAXIMIZE',
                'bobot' => 30.00,
                'target' => null,
                'tahun' => 2026,
                'target_jan' => null,
                'target_feb' => null,
                'target_mar' => null,
                'target_apr' => null,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 12,
                'bidang' => 'Pemasaran',
                'indikator' => 'Penjualan TL',
                'satuan' => 'GWh',
                'polaritas' => 'MAXIMIZE',
                'bobot' => 25.00,
                'target' => null,
                'tahun' => 2026,
                'target_jan' => null,
                'target_feb' => null,
                'target_mar' => null,
                'target_apr' => null,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 47,
                'bidang' => 'Transaksi Energi',
                'indikator' => 'Ganti Meter',
                'satuan' => 'Unit',
                'polaritas' => 'MAXIMIZE',
                'bobot' => 30.00,
                'target' => 26,
                'tahun' => 2026,
                'target_jan' => null,
                'target_feb' => null,
                'target_mar' => null,
                'target_apr' => null,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => 26,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => '{"jul":false}',
            ],
            [
                'id' => 1,
                'bidang' => 'Jaringan',
                'indikator' => 'Rating Negatif PLN Mobile',
                'satuan' => '%',
                'polaritas' => 'MIN',
                'bobot' => 5.00,
                'target' => 5,
                'tahun' => 2026,
                'target_jan' => 1,
                'target_feb' => 1,
                'target_mar' => 3,
                'target_apr' => 3,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 24,
                'bidang' => 'Jaringan',
                'indikator' => 'MTTR Siaga 1',
                'satuan' => '%',
                'polaritas' => 'MAXIMIZE',
                'bobot' => 10.00,
                'target' => null,
                'tahun' => 2026,
                'target_jan' => 100,
                'target_feb' => 95,
                'target_mar' => 91,
                'target_apr' => 92,
                'target_mei' => 99,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => '{"jan":true,"feb":true,"mar":true,"apr":true,"mei":true}',
            ],
            [
                'id' => 28,
                'bidang' => 'Jaringan',
                'indikator' => 'Gangguan TM > 5 Menit',
                'satuan' => null,
                'polaritas' => 'MAXIMIZE',
                'bobot' => null,
                'target' => null,
                'tahun' => 2026,
                'target_jan' => 2,
                'target_feb' => 1,
                'target_mar' => 1,
                'target_apr' => 1,
                'target_mei' => 2,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 31,
                'bidang' => 'Jaringan',
                'indikator' => 'Gangguan Trafo',
                'satuan' => 'Kali',
                'polaritas' => 'MINIMIZE',
                'bobot' => 10.00,
                'target' => null,
                'tahun' => 2026,
                'target_jan' => 2,
                'target_feb' => 2,
                'target_mar' => 1,
                'target_apr' => null,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 32,
                'bidang' => 'Jaringan',
                'indikator' => 'MVOD - SLA Gardu Induk',
                'satuan' => 'Menit',
                'polaritas' => 'MINIMIZE',
                'bobot' => 10.00,
                'target' => null,
                'tahun' => 2024,
                'target_jan' => null,
                'target_feb' => null,
                'target_mar' => null,
                'target_apr' => null,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 33,
                'bidang' => 'Jaringan',
                'indikator' => 'MVOD - SLA JTM',
                'satuan' => 'Menit',
                'polaritas' => 'MINIMIZE',
                'bobot' => 10.00,
                'target' => null,
                'tahun' => 2024,
                'target_jan' => null,
                'target_feb' => null,
                'target_mar' => null,
                'target_apr' => null,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 34,
                'bidang' => 'Jaringan',
                'indikator' => 'MVOD - SLA Gardu Distribusi',
                'satuan' => 'Menit',
                'polaritas' => 'MINIMIZE',
                'bobot' => 10.00,
                'target' => null,
                'tahun' => 2024,
                'target_jan' => null,
                'target_feb' => null,
                'target_mar' => null,
                'target_apr' => null,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 35,
                'bidang' => 'Jaringan',
                'indikator' => 'MVOD - SLA Gardu Induk',
                'satuan' => 'Menit',
                'polaritas' => 'MINIMIZE',
                'bobot' => 10.00,
                'target' => null,
                'tahun' => 2025,
                'target_jan' => null,
                'target_feb' => null,
                'target_mar' => null,
                'target_apr' => null,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 36,
                'bidang' => 'Jaringan',
                'indikator' => 'MVOD - SLA JTM',
                'satuan' => 'Menit',
                'polaritas' => 'MINIMIZE',
                'bobot' => 10.00,
                'target' => null,
                'tahun' => 2025,
                'target_jan' => null,
                'target_feb' => null,
                'target_mar' => null,
                'target_apr' => null,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 37,
                'bidang' => 'Jaringan',
                'indikator' => 'MVOD - SLA Gardu Distribusi',
                'satuan' => 'Menit',
                'polaritas' => 'MINIMIZE',
                'bobot' => 10.00,
                'target' => null,
                'tahun' => 2025,
                'target_jan' => null,
                'target_feb' => null,
                'target_mar' => null,
                'target_apr' => null,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 41,
                'bidang' => 'Jaringan',
                'indikator' => 'MVOD - SLA Gardu Induk',
                'satuan' => 'Menit',
                'polaritas' => 'MINIMIZE',
                'bobot' => 10.00,
                'target' => null,
                'tahun' => 2027,
                'target_jan' => null,
                'target_feb' => null,
                'target_mar' => null,
                'target_apr' => null,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 42,
                'bidang' => 'Jaringan',
                'indikator' => 'MVOD - SLA JTM',
                'satuan' => 'Menit',
                'polaritas' => 'MINIMIZE',
                'bobot' => 10.00,
                'target' => null,
                'tahun' => 2027,
                'target_jan' => null,
                'target_feb' => null,
                'target_mar' => null,
                'target_apr' => null,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 43,
                'bidang' => 'Jaringan',
                'indikator' => 'MVOD - SLA Gardu Distribusi',
                'satuan' => 'Menit',
                'polaritas' => 'MINIMIZE',
                'bobot' => 10.00,
                'target' => null,
                'tahun' => 2027,
                'target_jan' => null,
                'target_feb' => null,
                'target_mar' => null,
                'target_apr' => null,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 48,
                'bidang' => 'Transaksi Energi',
                'indikator' => 'Ganti Meter',
                'satuan' => null,
                'polaritas' => 'MAXIMIZE',
                'bobot' => null,
                'target' => 20,
                'tahun' => 2027,
                'target_jan' => 20,
                'target_feb' => 0,
                'target_mar' => 0,
                'target_apr' => 0,
                'target_mei' => 0,
                'target_jun' => 0,
                'target_jul' => 0,
                'target_agu' => 0,
                'target_sep' => 0,
                'target_okt' => 0,
                'target_nov' => 0,
                'target_des' => 0,
                'is_override' => null,
            ],
            [
                'id' => 45,
                'bidang' => 'Transaksi Energi',
                'indikator' => 'Perolehan kWh P2TL',
                'satuan' => 'kWh',
                'polaritas' => 'MAXIMIZE',
                'bobot' => 3.00,
                'target' => 7684,
                'tahun' => 2026,
                'target_jan' => 749957,
                'target_feb' => 749957,
                'target_mar' => 749957,
                'target_apr' => 749957,
                'target_mei' => 749957,
                'target_jun' => 749957,
                'target_jul' => 749957,
                'target_agu' => 749957,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => '{"jan":true,"feb":true,"mar":true,"apr":true,"mei":true,"jun":true,"jul":true,"agu":true}',
            ],
            [
                'id' => 2,
                'bidang' => 'Pemasaran',
                'indikator' => 'Daya Tersambung',
                'satuan' => 'MVA',
                'polaritas' => 'MAXIMIZE',
                'bobot' => 25.00,
                'target' => null,
                'tahun' => 2026,
                'target_jan' => null,
                'target_feb' => null,
                'target_mar' => null,
                'target_apr' => null,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 22,
                'bidang' => 'Jaringan',
                'indikator' => 'Gangguan TM',
                'satuan' => 'Kali',
                'polaritas' => 'MINIMIZE',
                'bobot' => 10.00,
                'target' => null,
                'tahun' => 2026,
                'target_jan' => null,
                'target_feb' => null,
                'target_mar' => null,
                'target_apr' => null,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 3,
                'bidang' => 'Pemasaran',
                'indikator' => 'PLN Mobile Transaksi',
                'satuan' => 'kali',
                'polaritas' => 'MAXIMIZE',
                'bobot' => 10.00,
                'target' => null,
                'tahun' => 2026,
                'target_jan' => null,
                'target_feb' => null,
                'target_mar' => null,
                'target_apr' => null,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 30,
                'bidang' => 'Jaringan',
                'indikator' => 'Gangguan Switching',
                'satuan' => 'Kali',
                'polaritas' => 'MINIMIZE',
                'bobot' => 10.00,
                'target' => null,
                'tahun' => 2026,
                'target_jan' => 1,
                'target_feb' => 1,
                'target_mar' => 2,
                'target_apr' => 2,
                'target_mei' => 3,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 4,
                'bidang' => 'Niaga',
                'indikator' => 'Pelunasan PRR & Piutang',
                'satuan' => 'Rp Miliar',
                'polaritas' => 'MAXIMIZE',
                'bobot' => 40.00,
                'target' => null,
                'tahun' => 2026,
                'target_jan' => null,
                'target_feb' => null,
                'target_mar' => null,
                'target_apr' => null,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 5,
                'bidang' => 'Aset',
                'indikator' => 'Penambahan Aset Fisik AI',
                'satuan' => 'Unit',
                'polaritas' => 'MAXIMIZE',
                'bobot' => 30.00,
                'target' => null,
                'tahun' => 2026,
                'target_jan' => null,
                'target_feb' => null,
                'target_mar' => null,
                'target_apr' => null,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 6,
                'bidang' => 'Aset',
                'indikator' => 'Penambahan Aset RUPTL',
                'satuan' => 'Unit',
                'polaritas' => 'MAXIMIZE',
                'bobot' => 30.00,
                'target' => null,
                'tahun' => 2026,
                'target_jan' => null,
                'target_feb' => null,
                'target_mar' => null,
                'target_apr' => null,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 7,
                'bidang' => 'Pemasaran',
                'indikator' => 'Jumlah Pelanggan',
                'satuan' => 'plg',
                'polaritas' => 'MAXIMIZE',
                'bobot' => 25.00,
                'target' => null,
                'tahun' => 2026,
                'target_jan' => null,
                'target_feb' => null,
                'target_mar' => null,
                'target_apr' => null,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 38,
                'bidang' => 'Jaringan',
                'indikator' => 'MVOD - SLA Gardu Induk',
                'satuan' => 'Menit',
                'polaritas' => 'MINIMIZE',
                'bobot' => 10.00,
                'target' => null,
                'tahun' => 2026,
                'target_jan' => 40,
                'target_feb' => 30,
                'target_mar' => null,
                'target_apr' => null,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 39,
                'bidang' => 'Jaringan',
                'indikator' => 'MVOD - SLA JTM',
                'satuan' => 'Menit',
                'polaritas' => 'MINIMIZE',
                'bobot' => 10.00,
                'target' => null,
                'tahun' => 2026,
                'target_jan' => 30,
                'target_feb' => 45,
                'target_mar' => null,
                'target_apr' => null,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 40,
                'bidang' => 'Jaringan',
                'indikator' => 'MVOD - SLA Gardu Distribusi',
                'satuan' => 'Menit',
                'polaritas' => 'MINIMIZE',
                'bobot' => 10.00,
                'target' => null,
                'tahun' => 2026,
                'target_jan' => 20,
                'target_feb' => 27,
                'target_mar' => null,
                'target_apr' => null,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 29,
                'bidang' => 'Jaringan',
                'indikator' => 'Gangguan TM < 5 Menit',
                'satuan' => null,
                'polaritas' => 'MAXIMIZE',
                'bobot' => null,
                'target' => null,
                'tahun' => 2026,
                'target_jan' => 2,
                'target_feb' => 2,
                'target_mar' => 1,
                'target_apr' => 1,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 44,
                'bidang' => 'test',
                'indikator' => 'test',
                'satuan' => 'test',
                'polaritas' => 'MAXIMIZE',
                'bobot' => 10.00,
                'target' => 100,
                'tahun' => 2026,
                'target_jan' => null,
                'target_feb' => null,
                'target_mar' => null,
                'target_apr' => null,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 26,
                'bidang' => 'Jaringan',
                'indikator' => 'RPT G (Tanpa CT)',
                'satuan' => 'Menit',
                'polaritas' => 'MINIMIZE',
                'bobot' => 10.00,
                'target' => null,
                'tahun' => 2026,
                'target_jan' => 30,
                'target_feb' => 3,
                'target_mar' => 1,
                'target_apr' => null,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 14,
                'bidang' => 'Pemasaran',
                'indikator' => 'PLN Mobile Nilai',
                'satuan' => 'Rp Miliar',
                'polaritas' => 'MAXIMIZE',
                'bobot' => 10.00,
                'target' => null,
                'tahun' => 2026,
                'target_jan' => null,
                'target_feb' => null,
                'target_mar' => null,
                'target_apr' => null,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 15,
                'bidang' => 'Jaringan',
                'indikator' => 'SAIDI',
                'satuan' => 'menit/pelanggan',
                'polaritas' => 'MINIMIZE',
                'bobot' => 30.00,
                'target' => 0.0003,
                'tahun' => 2026,
                'target_jan' => 0.0003,
                'target_feb' => 0.0003,
                'target_mar' => 0.0003,
                'target_apr' => 0.0006,
                'target_mei' => 0.0002,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 16,
                'bidang' => 'Jaringan',
                'indikator' => 'SAIFI',
                'satuan' => 'kali/pelanggan',
                'polaritas' => 'MINIMIZE',
                'bobot' => 30.00,
                'target' => null,
                'tahun' => 2026,
                'target_jan' => 0.0004,
                'target_feb' => 0.0002,
                'target_mar' => 0.0001,
                'target_apr' => 0.0003,
                'target_mei' => 0.0005,
                'target_jun' => 0.0002,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 17,
                'bidang' => 'Keuangan',
                'indikator' => 'Saldo Rata-Rata Akhir Bulan',
                'satuan' => 'Rp Miliar',
                'polaritas' => 'MAXIMIZE',
                'bobot' => 30.00,
                'target' => null,
                'tahun' => 2026,
                'target_jan' => null,
                'target_feb' => null,
                'target_mar' => null,
                'target_apr' => null,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 18,
                'bidang' => 'Keuangan',
                'indikator' => 'Success Rate',
                'satuan' => '%',
                'polaritas' => 'MAXIMIZE',
                'bobot' => 40.00,
                'target' => null,
                'tahun' => 2026,
                'target_jan' => null,
                'target_feb' => null,
                'target_mar' => null,
                'target_apr' => null,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 19,
                'bidang' => 'Transaksi Energi',
                'indikator' => 'Susut',
                'satuan' => '%',
                'polaritas' => 'MINIMIZE',
                'bobot' => 40.00,
                'target' => null,
                'tahun' => 2026,
                'target_jan' => 5.43,
                'target_feb' => 5.41,
                'target_mar' => 5.4,
                'target_apr' => 5.38,
                'target_mei' => 5.36,
                'target_jun' => 5.34,
                'target_jul' => 5.32,
                'target_agu' => 5.3,
                'target_sep' => 5.28,
                'target_okt' => 5.26,
                'target_nov' => 5.24,
                'target_des' => 5.23,
                'is_override' => '{"jan":true,"feb":true,"mar":true,"apr":true,"mei":true,"jun":true,"jul":true,"agu":true,"sep":true,"okt":true,"nov":true,"des":true}',
            ],
            [
                'id' => 20,
                'bidang' => 'Niaga',
                'indikator' => 'Tindak Lanjut LBKB',
                'satuan' => 'Laporan',
                'polaritas' => 'MAXIMIZE',
                'bobot' => 30.00,
                'target' => null,
                'tahun' => 2026,
                'target_jan' => null,
                'target_feb' => null,
                'target_mar' => null,
                'target_apr' => null,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 21,
                'bidang' => 'Jaringan',
                'indikator' => 'ENS',
                'satuan' => 'MWh',
                'polaritas' => 'MINIMIZE',
                'bobot' => 20.00,
                'target' => null,
                'tahun' => 2026,
                'target_jan' => 0.0001,
                'target_feb' => 0.0001,
                'target_mar' => 0.0002,
                'target_apr' => 0.0003,
                'target_mei' => null,
                'target_jun' => null,
                'target_jul' => null,
                'target_agu' => null,
                'target_sep' => null,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
            [
                'id' => 27,
                'bidang' => 'Jaringan',
                'indikator' => 'SRDAG',
                'satuan' => 'Kali',
                'polaritas' => 'MINIMIZE',
                'bobot' => 10.00,
                'target' => null,
                'tahun' => 2026,
                'target_jan' => 100,
                'target_feb' => 100,
                'target_mar' => 30,
                'target_apr' => 40,
                'target_mei' => 56,
                'target_jun' => 70,
                'target_jul' => 56,
                'target_agu' => 50,
                'target_sep' => 50,
                'target_okt' => null,
                'target_nov' => null,
                'target_des' => null,
                'is_override' => null,
            ],
        ];

        // Insert in chunks to avoid large query errors
         = array_chunk($data, 50);
        foreach ($chunks as $chunk) {
            DB::table('targets')->insert($chunk);
        }
    }
}
